### PR TITLE
#44

### PR DESCRIPTION
**Pull request by anilkhandei**
## Pull Requests

Added: `Setting<T>` class
Modified: 
1. `Setting GetSetting` to `Setting<T> GetSetting<T>`
2. Updated all references of `GetSetting` method to use new 'GetSetting<T>' method

 Pull request rules:

 1. Clearly describe changes, as detailed as possible
 2. If possible, show examples of usage
 3. Ensure any install or build dependencies are removed before the end of the layer when doing a build.
 4. Make sure all tests are passing.

### CODE REVIEW

**Comment by flabbet** [comment]
Please fix tests :)

**Comment by anilkhandei** [comment]
I forgot to checkin the same. Please re validate.

pixitests_44

**Comment by flabbet** [comment]
This is okay, but much better solution would be to provide a type of setting class, instead of value type. Because we know the setting we want to get, not necessarily the type it returns. 

For example instead `GetSetting<int>("ToolSize")` would be `GetSetting<SizeSetting>("ToolSize")

And return type would be `SizeSetting`

Could you change `GetSetting<T>` so `T` is a child class of `Setting`? And create a overload for `GetSetting` that doesn't need `T`?

**Comment by ArtemK123** [comment]
Ok, I understand what you want.
I will do it in a couple of days, just wait for the updates ;-)

**Comment by ArtemK123** [comment]
Hi. Maybe it is better to close that pull request, cause you have already merged my pull request related to the same issue.

**Comment by flabbet** [comment]
Closed in #66

**Pull request closed without merging**
