### PR TITLE
Limit big file loading for recent opened files

### LINKED ISSUE #220: Don't load big files in startup window
Currently all files are loaded when the startup window is opened, which might crash PixiEditor because of too much memory consumption.

Checking the file size is probably not enough so checking the width and height of the document/image headers should work

### PR DESCRIPTION
**Pull request by Xiphereal**
This PR resolves #220.

## TODO:
- [x] Limit loading of big Pixi files.
- [x] Limit loading of image files (.png, .jpg & .jpeg).

### CODE REVIEW

**Comment by Xiphereal** [comment]
As we discussed on Discord, storing the already clamped PreviewImage for the Pixi files would be a nice solution for taking away the maximum file size check from the recent opened files.

**Comment by Xiphereal** [comment]
> Any progress?
I've been busy these days. I plan on finishing this as soon as I can :)

**Review by flabbet — APPROVED** [review]
Awesome, great job

**Comment by flabbet** [comment]
Do you want to add anything or can I merge?

**Comment by Xiphereal** [comment]
> 
> 
> Do you want to add anything or can I merge?

For me it's okkey, merge as it is :)

**Pull request merged**
