### PR TITLE
Fix the center issue.

### PR DESCRIPTION
**Pull request by PtrStruct**
## Pull Requests
#406 

The titlebar items were not aligned, so I fixed the margins.

 Pull request rules:

 1. Clearly describe changes, as detailed as possible
 2. If possible, show examples of usage
 3. Ensure any install or build dependencies are removed before the end of the layer when doing a build.
 4. Make sure all tests are passing.

### CODE REVIEW

**Comment by PtrStruct** [comment]
Is it common for it to fail the Azure pipeline build?

**Comment by Equbuxu** [comment]
> Is it common for it to fail the Azure pipeline build? Or did I miss something super obvious?

Yeah, don't worry about the pipelines, they've been failing for a while now for some non-obvious reason

**Comment by Equbuxu** [comment]
Looks good to me, here is a quick comparison for others to check out

https://user-images.githubusercontent.com/29402050/176998444-68941d01-beef-4f62-8140-350d5d8eeb65.mp4

**Comment by PtrStruct** [comment]
Thanks for posting a before and after video! I realized my PR message was pretty vague and I should of done what you just did to begin with. Either way, it's much appreciated!

**Review by flabbet — APPROVED** [review]

**Pull request merged**
