### PR TITLE
Added a static code analyze (resolve issue 74)

### PR DESCRIPTION
**Pull request by ArtemK123**
## Pull Requests

 Pull request rules:

 1. Clearly describe changes, as detailed as possible
I have added a static analyzer. For that I did the following:
 - Moved .sln file on the top level of the repository
 - Created Directory.build.props file, which is used for storing parts of .csproj configuration for each project.
 - Added support of StyleCop.Analyzers - added the nuget reference in Directory.build.props and two configuration files - Custom.ruleset and stylecop.json
 - Created virtual folder in .sln file - BuildConfiguration. Placed the above-described files in that folder.

 2. If possible, show examples of usage
You can configure the analyzer in two ways:
- edit stylecop.json - it contains common configurations. You can find more at https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md
- edit Custom.ruleset - via that file you can configure the severity for each warning (the warning's id will be highlighted by IDE). Example of usage:
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Name" Description="Description" ToolsVersion="15.0">
    <Rules AnalyzerId="StyleCop.Analyzers" RuleNamespace="StyleCop.Analyzers">
		<Rule Id="SA1101" Action="None" />
		<Rule Id="SA1633" Action="None" />
		<Rule Id="SA1650" Action="None" />
		<Rule Id="SA1652" Action="None" />
    </Rules>
</RuleSet>

 3. Ensure any install or build dependencies are removed before the end of the layer when doing a build.
The whole task is about adding the build dependency :)

 4. Make sure all tests are passing.
All of them are green

5. Comments
I have left the default configuration of the analyzer. I will recommend you to edit the configuration files to make them in line with your coding style.

### CODE REVIEW

**Comment by flabbet** [comment]
Holy shit xd 
image
Nice, I'll take a look at it tomorrow

**Comment by flabbet** [comment]
I was wondering, is there a way to apply all fixed to style warnings, resharper or sth?

**Comment by ArtemK123** [comment]
I have found this article with useful tools, but I haven`t tried any of them.
https://stackoverflow.com/questions/1359819/is-there-a-stylecop-fxcop-autofixing-tool

I can try some of them. If I find something useful - I will write.
Anyway, it will be more productive if you firstly form the final code-style settings and the final warning`s count is visible.

**Comment by flabbet** [comment]
Okay, so I edited Custom.ruleset
```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Name" Description="Description" ToolsVersion="16.0">
  <Rules AnalyzerId="StyleCop.Analyzers" RuleNamespace="StyleCop.Analyzers">
    <Rule Id="SA1101" Action="None" />
  </Rules>
</RuleSet>
```
The rest of the default settings is okay, at least for now. However, automating fixing the warnings is a key, I won't change 2k+ style warnings by hand.

**Comment by ArtemK123** [comment]
It was pretty hard, but I have tried to fix all of the warnings :-)
Currently, there are only 18 warnings in case of dotnet build command on PixiEditor.sln. I think, almost all of the warnings were presented before the static analyzer

P.S. : I have increased the version of StyleCop.Analyzer, so from now you can use the auto-fix in Visual studio out-of-the-box for a lot of warnings.

**Comment by ArtemK123** [comment]
I have also edited ruleset, I think you should take a look on this.
Sorry for merges, I have forgotten to pull the changes to my forked repo before the delivering

**Review by flabbet — COMMENTED** [review]
Okay, this is nice, could you fix merge conflicts and I'll merge your PR

**Comment by ArtemK123** [comment]
I made a merge and fixed all warnings caused by it. For now, there are only 18 warnings in my IDE.

**Comment by ArtemK123** [comment]
I have also edited Custom.ruleset and disabled some of the warnings.

**Review by flabbet — APPROVED** [review]
Awesome work

**Pull request merged**
