### PR TITLE
Fixed some StorageBasedUndo cases?

### PR DESCRIPTION
**Pull request by flabbet**
I fixed a few particular cases. Although please try to break it and if successfully, try to reproduce steps with small canvas size.

Case fixed:

https://user-images.githubusercontent.com/25402427/152863880-a1296b6d-8a28-4265-899d-c5575f7a5134.mp4

### CODE REVIEW

**Comment by Equbuxu** [comment]
Here is a case where in breaks
https://user-images.githubusercontent.com/29402050/153285385-c9c20064-8c1c-4a9c-ab7e-310f33984db8.mp4

**Comment by flabbet** [comment]
@Equbuxu review pls

**Comment by flabbet** [comment]
I think I fixed now. Please review again. I am still able to reproduce some resizing issues. But I think I fixed cases mentioned here

**Comment by Equbuxu** [comment]
> I think I fixed now. Please review again. I am still able to reproduce some resizing issues. But I think I fixed cases mentioned here

Can confirm that everything from the videos seems to be fixed. There are still issues when using the other anchor points but I'm assuming you know about those

**Comment by flabbet** [comment]
Fixed other anchors

**Comment by flabbet** [comment]
Fixed #325

**Comment by flabbet** [comment]
Seems like I resolved it

**Review by Equbuxu — CHANGES_REQUESTED** [review]
So ... I re-tested everything from the videos in this PR and literally every single video caused pixieditor to break .. lol

#325 seems to be fixed

**Comment by Equbuxu** [comment]
The steps in the last video still break PixiEditor

**Comment by flabbet** [comment]
Seems like your rect based undo impl works flawless

**Review by CPKreuz — APPROVED** [review]

**Pull request merged**
