### PR TITLE
Improved touch and stylus support

### PR DESCRIPTION
**Pull request by CPKreuz**

### CODE REVIEW

**Comment by flabbet** [comment]
So this PR is without reference layer right?

**Comment by CPKreuz** [comment]
Nope, but I will force push in a bit

**Comment by flabbet** [comment]
It feels a little laggy to use

**Review by flabbet — CHANGES_REQUESTED** [review]
Touch gestures work, new file animation is nice, but drawing using touch screen doesn't work

**Review by flabbet — CHANGES_REQUESTED** [review]
When opening a document, you can't zoom using touch, you need to select any tool, event selected one, then it works

**Review by flabbet — APPROVED** [review]
Everything looks good

**Comment by CPKreuz** [comment]
This should also fix #188

**Pull request merged**
