### PR TITLE
Windows explorer image preview #140

### PR DESCRIPTION
**Pull request by tomaszkot**
This is the 1st working approach.
This is a native code relaying on the PixiEditor making a temporary image during save. See changes in Exporter SaveAsEditableFile. 
Since PixiEditor is an application I can not reuse its code to load a thumbnail preview.
Maybe in the future app's code loading images could be extracted to a dll, then it would be possible to use that code from a native code.
So, the current limitation is that if someone makes a copy of the pixi file in windows thumbnail  will not be changes until file is opened and saved in the application.

To test it: Go to \Installer\PixiThumbnails and run InstallPixiThumbnailProviderServer.bat
That's it.

Installer must be changed to :
1. Install PixiThumbnailProvider.dll from PixiEditor\Installer\PixiThumbnails and bat files to the app's folder
2. Issue the commands from bat files from app's dirctory. There shall be a silent option used /s -  Prevents displaying messages.

### CODE REVIEW

**Comment by flabbet** [comment]
So technically, if there was C++ native code PixiParser implementation, no temporary image would be needed? All of the files would load, no matter if opened and saved again?

**Comment by tomaszkot** [comment]
> So technically, if there was C++ native code PixiParser implementation, no temporary image would be needed? All of the files would load, no matter if opened and saved again?

No need to have any native code in Pixi. I meant extracting parts of the app into a .net dll. That would be a good move anyway and would allow to write a bridge from c++ to C# using e.g. CLI c++.

**Comment by flabbet** [comment]
Ah, ofc. We are going to extract parts of the app into separate dlls, but PixiParser is already a separate dll

**Comment by tomaszkot** [comment]
> Ah, ofc. We are going to extract parts of the app into separate dlls, but PixiParser is already a separate dll

OK, Then I would provide an alternative implementation of Thumbnails using PixiParser. I'd leave pure native (relying on temp save file) as alternative one.

**Comment by flabbet** [comment]
Also, small PixiEditor icon in bottom right corner is required, otherwise people might confuse it with PNG or JPG 
image

**Comment by tomaszkot** [comment]
> Also, small PixiEditor icon in bottom right corner is required, otherwise people might confuse it with PNG or JPG
> 
> This is how Affinity Photo does that image

Yeah, shall be easy to add...

**Comment by tomaszkot** [comment]
image

Almost there!

**Comment by tomaszkot** [comment]
Some considerations for the new Native+CLR approach vs prev native-only approach:
pros :
- Copy of a pixi file instantly gets proper thumbnail
- No additional save to png needed in PixiEditor

cons:
- Two more projects (CLR - native to .NETBridge, .NetThumbnailProvider - preparing thumbnail using PixiParser.Skia.dll)
- Could not debug CLR  and .NET projects. Not a big deal, and probably could be asked on SO, saw there hints for .net 4.0 but not for 6.0
- I have lot's of ugly warnings like : c:\windows\assembly\gac_64\system.data\2.0.0.0__b77a5c561934e089\system.data.dll : warning C4945: 'IDataRecord': cannot import symbol from 'c:\windows\assembly\gac_64\system.data\2.0.0.0__b77a5c561934e089\system.data.dll': as 'System::Data::IDataRecord' has already been imported from another assembly 'System.Data.Common'
Do not know how to fix it, maybe this is just my local pc problem.

**Comment by flabbet** [comment]
Nice! Here is full res logo you can use.

PixiEditorLogo
d

**Comment by tomaszkot** [comment]
I'd provide code soon, maybe tomorrow.  I was going to provide both options Native and Native_CLR_NET switchable in the PixiEditor config file, but I'm not sure this is needed from your point of view.

**Comment by tomaszkot** [comment]
I think I have done it, yet on CI it shows a strange error :/ :
Project PixiCLRBridge is not compatible with native (native,Version=v0.0). Project PixiCLRBridge supports: net6.0-windows10.0.22000 (.NETCoreApp,Version=v6.0)

**Comment by Equbuxu** [comment]
Just a note: we haven't forgotten about this PR, the current idea is to add a small pre-rendered preview png into .pixi and load it from C++. It will be added in the next PixiParser version. This way the C++ code will be way simpler, there will be no need for C++/C# interop and we won't need to update the rendering code as PixiEditor gets more advanced features, like blend modes, clip to layer below, etc.

**Comment by tomaszkot** [comment]
> Just a note: we haven't forgotten about this PR, the current idea is to add a small pre-rendered preview png into .pixi and load it from C++. It will be added in the next PixiParser version. This way the C++ code will be way simpler, there will be no need for C++/C# interop and we won't need to update the rendering code as PixiEditor gets more advanced features, like blend modes, clip to layer below, etc.

Glad to hear it, let me know once the version with preview is ready.

**Comment by Equbuxu** [comment]
@tomaszkot Hey, the .pixi file format was finally updated to include a pre-rendered preview, so if you want, you can finally continue working on this PR. Please let us know if are still interested in that. If you don't, that's okay, we will most likely merge your PR anyway and update the code ourselves.

**Comment by tomaszkot** [comment]
OK, I'll have a look and let you know soon.

**Pull request closed without merging**
