### PR TITLE
Added grid lines

### PR DESCRIPTION
**Pull request by flabbet**
Solves #45.

Toggle grid lines available under Views Menu
Shortcut for toggling: Ctrl + `

### CODE REVIEW

**Review by CPKreuz — CHANGES_REQUESTED** [review]
Can you make the lines dashed? And the dashed ones in a different color.
They should also be in front of preview layers

**Comment by flabbet** [comment]
Dashed like an option or instead of solid ones?

**Comment by flabbet** [comment]
Fixed

**Review by CPKreuz — CHANGES_REQUESTED** [review]
Only 10% of the canvas is dashed now?

weridDashButOk

**Review by CPKreuz — CHANGES_REQUESTED** [review]
Can you also add a line that marks the middle

**Comment by flabbet** [comment]
This would be a part of guides.
And not all canvas sizes have a middle line. So it's outside of the scope of this PR

**Pull request merged**
