### PR TITLE
PixiThumbnailProvider 0.9 done in native mode

### PR DESCRIPTION
**Pull request by tomaszkot**
This is a native implementation of Thumbnail Provider based on the pixi preview data from a file's header.

To test it run a InstallPixiThumbnailProviderServer.bat file at PixiThumbnailProvider.

TODO: add an icon of the app in the  lower right corner.

### CODE REVIEW

**Comment by Equbuxu** [comment]
Wow, that was quick! I'll have to review it today, the PR might just make it into the 1.0 release

**Comment by tomaszkot** [comment]
Theoretically it was very simple, but I had a trouble with interpreting array of bytes describing preview size. In .net   there is BitConverter, in c++ you have to write it. It's working, though not supporting that big-endian and little-endian checks,  so currently it will not work on Power PC. I can improve it of you support such architecture. 

Today I'll try to add that app's icon in the corner of the thumbnail.

**Review by Equbuxu — APPROVED** [review]
Looks good, for me the thumbnails already have the pixieditor logo in the corner (might be a win 11 thing?)

**Comment by flabbet** [comment]
I'm gonna do a proper review in a few days, I don't want to risk releasing it to 1.0, it's too little time to test it properly

**Comment by tomaszkot** [comment]
> ...for me the thumbnails already have the pixieditor logo in the corner (might be a win 11 thing?)

Wow, I do not have win11 so can not tell, doing it  is possible, yet again not a piece of cake as loading pixi logo from rc file in c++ would be a nasty piece of code.

**Pull request merged**
