### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by flabbet**
PR with fixes to bugs found in 0.1.7.1-dev 

- [X] #350 
- [x] #349 
- [x] #351 
- [x] #358
- [x] #359 
- [x] Group previews not working
- [x] #329 
- [x]  #348 
- [x] #354 
- [x] #364 
- [x] #363

### CODE REVIEW

**Review by Equbuxu — CHANGES_REQUESTED** [review]
Move tool and move viewport tool seem to work fine, #351 still isn't fixed

**Comment by flabbet** [comment]
Fixed

**Review by Equbuxu — CHANGES_REQUESTED** [review]
- A bug with shortcuts:

1. Select the pen tool
2. Press space and move the canvas a bit
3. Release space
4. Press E (don't hold it down) to switch to the eraser tool

Expected result: the eraser tool should be selected
Actual result: the eraser tool is briefly selected while the E key is down and then the selection goes back to the pen tool.

- Steps from #358 lead to an infinite save loop

**Comment by flabbet** [comment]
Fixed both

**Review by Equbuxu — COMMENTED** [review]
The image preview in the taskbar doesn't seem to be updated when you make a new document (or open an existing one). Not really sure if that's a bug. All else seems good

**Comment by Equbuxu** [comment]
nvm I broke something somehow

**Comment by Equbuxu** [comment]
https://user-images.githubusercontent.com/29402050/154840407-ca5e13e0-8fbe-4144-8b96-4f32a36d8b07.mp4

**Comment by flabbet** [comment]
Fixed

**Review by Equbuxu — CHANGES_REQUESTED** [review]
- The taskbar image preview is empty when loading a regular (non-.pixi) image
- Selection tool doesn't work, neither does Ctrl+A nor the move tool
- Crash when drawing on a pasted layer:
1. Paste an image
2. Draw something on the new layer
3. Undo 2x
4. Redo 2x
- A similar crash when deleting a pasted layer
1. Paste an image
2. Delete the pasted layer
3. Undo all the way
4. Redo all the way
It seems like any manipulations with the pasted layer cause pixieditor to crash in a similar way.

**Review by Equbuxu — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/29402050/154861864-e9b9ddbf-1966-4e97-9f00-fb66f105009d.mp4

**Review by Equbuxu — APPROVED** [review]

**Pull request merged**
