### PR TITLE
Add support to read DeluxePaint palettes

### PR DESCRIPTION
**Pull request by warrengalyen**

### CODE REVIEW

**Comment by flabbet** [comment]
Could you please provide a few files to test the parser with?

**Comment by warrengalyen** [comment]
Here you go. 
[DeluxePaint palettes.zip](https://github.com/PixiEditor/PixiEditor/files/13676346/DeluxePaint.palettes.zip)

**Review by Equbuxu — APPROVED** [review]
Looks good to me, works with your files as well as with files I exported from DeluxePaint myself (minus the extension in capital letters issue). Just curious, do you know of any modern software that uses these palette formats? I couldn't find any, so I resorted to running DeluxePaint in DOSBox

**Comment by warrengalyen** [comment]
No, I only know of software that supports reading them, but the format itself was only used by DeluxePaint on Amiga and DOS. I exported the palettes directly as well directly from DeluxePaint. Just thought it would be nice to support since it was a pretty popular editor for pixel art back in the day.

**Review by flabbet — APPROVED** [review]

**Pull request merged**
