### PR TITLE
Cropped layer previews

### PR DESCRIPTION
**Pull request by Equbuxu**

### CODE REVIEW

**Comment by Equbuxu** [comment]
I don't think anyone will understand the code, but please test very thoroughly (main previews, mask previews, layers, folders, etc.), I had so many crashes there is no way it works 100% now

**Review by flabbet — CHANGES_REQUESTED** [review]
Open an image from disk -> Select whole image pixels -> scale it down: preview bitmap is not cropped and won't be.

**Comment by flabbet** [comment]
Resizing Canvas causes a crash

**Review by flabbet — CHANGES_REQUESTED** [review]
Create a 64x64 canvas -> Draw something -> Resize canvas to 128x128 -> Undo.

Preview is weirdly duplicated

**Pull request merged**
