### PR TITLE
Zoom tool

### PR DESCRIPTION
**Pull request by flabbet**
Added Zoom tool and fixed editable textbox shortcut bug.

### CODE REVIEW

**Comment by flabbet** [comment]
@Equbuxu Could you check if it works well with a stylus?

**Comment by Equbuxu** [comment]
It does work with stylus about as well as it does with mouse. It works, but it will definitely require improvements in the future since:
1. It feels quite laggy, I believe this because the Use() function of the tool accepts integer coordinates instead of float or double
2. It should zoom towards mouse down position on the canvas, not towards center
3. In my opinion, it could be more sensetive

**Comment by flabbet** [comment]
It doesn't use integer `Use()` coordinates, I calculate drag with absolute screen position. I'll try to improve it.

**Comment by flabbet** [comment]
@Equbuxu Can you check now?

**Comment by flabbet** [comment]
Let me describe how it works: https://www.youtube.com/watch?v=YPN0qhSyWy8

**Comment by flabbet** [comment]
@Equbuxu Can you check now :)?

**Comment by flabbet** [comment]
Okay, merging it. #39 yet to be fixed in the future

**Pull request merged**
