### PR TITLE
Reference layer

### PR DESCRIPTION
**Pull request by flabbet**
Added reference layer in LayersManager window

### CODE REVIEW

**Review by CPKreuz — CHANGES_REQUESTED** [review]
1. You can select a preview layer even when there's no document opened

2. When you open a second document it shows that it has a reference layer even though it shouldn't

3. I think Add reference layer sounds better

**Review by CPKreuz — CHANGES_REQUESTED** [review]
Dragging Layers doesn't work

**Comment by flabbet** [comment]
Fixed

**Review by CPKreuz — COMMENTED** [review]
Just saw this in the last commit, use nameof(Property) instead of a string for properties and maybe make the `LayerGroupControlDataName` and `LayerContainerDataName` static and set the value to `typeof(LayerGroupControl).FullName`

**Comment by flabbet** [comment]
Oh, I didn't know about `typeof(x).FullName` thing

**Review by CPKreuz — APPROVED** [review]

**Review by Equbuxu — COMMENTED** [review]
Fix warnings

**Review by Equbuxu — CHANGES_REQUESTED** [review]
wrong type of review

**Review by Equbuxu — APPROVED** [review]

**Pull request merged**
