### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by flabbet**
I don't actually expect all of you to review everything, but try checking if you can crash palette browser and test if supporter pack works for you

### CODE REVIEW

**Review by CPKreuz — CHANGES_REQUESTED** [review]
Localization not working

image

When hovering the image the title should become white too and use CultureInfo.CurrentCulture with the 'd' date format

**Comment by flabbet** [comment]
> 1. Localization not working

Because localization file is in extension, and you don't have it installed

> 2. When hovering the image the title should become white too and use CultureInfo.CurrentCulture with the 'd' date format

I use 'd' date format in XAML

> 3. Also the window sizing should be adjusted so that the recent documents don't scroll

Sure

**Comment by CPKreuz** [comment]
> I use 'd' date format in XAML

but not the right culture

**Comment by flabbet** [comment]
Fixed most of the issues (besides white link text on image hover, because I got too frustrated while implementing that xd)

**Review by CPKreuz — CHANGES_REQUESTED** [review]
Using a unkown news type breaks the fetching.
Also I don't think any new users installing PixiEditor should be bombarded with news. Maybe keep the pane closed and mark all news as already closed if it's the first time opening PixiEditor

**Pull request merged**
