### PR TITLE
Handled update settings for UPDATE and non update platforms

### PR DESCRIPTION
**Pull request by flabbet**
Steam and MSIX configuration now shows in settings "Handled by {platform}" in update stream and update checkbox is grayed out. Also updated MSIX project target platform 

#458

### CODE REVIEW

**Comment by CPKreuz** [comment]
why not grey out the combox box?

**Comment by flabbet** [comment]
I could do that, but then I'd have to make ComboBox very wide so it contains full "Handled by Microsoft Store" text. If it's not grayed out, then user can click on that and will see full name. It's of course fixable, but imo too much effort for almost the same effect

**Comment by flabbet** [comment]
Done

**Comment by flabbet** [comment]
Also hidden donation button for Steam

**Review by CPKreuz — APPROVED** [review]
Looks good

**Pull request merged**
